
import java.awt.Color;
import javax.swing.JSpinner;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class MapWindow extends javax.swing.JFrame {
            int count;

    MapController cont = new MapController();

    /**
     * Creates new form MapWindow
     */
    public MapWindow() {
        initComponents();

    }

    public void log() {

        if (cont.isCorrect(cont.getAnsw())) {
            score.setText("correct");
            score.setForeground(Color.green);
            
            acc.setText("");
            cont.chooseCity();
            name.setText(cont.getCity().get(cont.getrChosen()).toString());

        } else {
            score.setText("incorrect");
            score.setForeground(Color.red);
            this.count += 1;
                    acc.setText((String) cont.model.getCities().get(cont.getAnsw()));
                    System.out.println(cont.model.getCities().get(cont.getAnsw()));


        }

    }

    public int getSpin() {
        int value = (Integer) spin.getValue();
        return value;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t60 = new javax.swing.JButton();
        t59 = new javax.swing.JButton();
        t58 = new javax.swing.JButton();
        t57 = new javax.swing.JButton();
        t56 = new javax.swing.JButton();
        t55 = new javax.swing.JButton();
        t54 = new javax.swing.JButton();
        t53 = new javax.swing.JButton();
        t52 = new javax.swing.JButton();
        t51 = new javax.swing.JButton();
        t50 = new javax.swing.JButton();
        t49 = new javax.swing.JButton();
        t48 = new javax.swing.JButton();
        t47 = new javax.swing.JButton();
        t46 = new javax.swing.JButton();
        t45 = new javax.swing.JButton();
        t44 = new javax.swing.JButton();
        t43 = new javax.swing.JButton();
        t42 = new javax.swing.JButton();
        t41 = new javax.swing.JButton();
        t40 = new javax.swing.JButton();
        t39 = new javax.swing.JButton();
        t38 = new javax.swing.JButton();
        t37 = new javax.swing.JButton();
        t36 = new javax.swing.JButton();
        t35 = new javax.swing.JButton();
        t34 = new javax.swing.JButton();
        t33 = new javax.swing.JButton();
        t32 = new javax.swing.JButton();
        t31 = new javax.swing.JButton();
        t30 = new javax.swing.JButton();
        t29 = new javax.swing.JButton();
        t28 = new javax.swing.JButton();
        t27 = new javax.swing.JButton();
        t26 = new javax.swing.JButton();
        t25 = new javax.swing.JButton();
        t24 = new javax.swing.JButton();
        t23 = new javax.swing.JButton();
        t22 = new javax.swing.JButton();
        t21 = new javax.swing.JButton();
        t20 = new javax.swing.JButton();
        t19 = new javax.swing.JButton();
        t18 = new javax.swing.JButton();
        t17 = new javax.swing.JButton();
        t16 = new javax.swing.JButton();
        t15 = new javax.swing.JButton();
        t14 = new javax.swing.JButton();
        t13 = new javax.swing.JButton();
        t12 = new javax.swing.JButton();
        t11 = new javax.swing.JButton();
        t10 = new javax.swing.JButton();
        t9 = new javax.swing.JButton();
        t8 = new javax.swing.JButton();
        t7 = new javax.swing.JButton();
        t6 = new javax.swing.JButton();
        t5 = new javax.swing.JButton();
        t4 = new javax.swing.JButton();
        t3 = new javax.swing.JButton();
        t2 = new javax.swing.JButton();
        t1 = new javax.swing.JButton();
        t0 = new javax.swing.JButton();
        spin = new javax.swing.JSpinner();
        spinbut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        map = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t0.setOpaque(false);
        t60.setBackground(new java.awt.Color(0,0,0,0));
        t60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t60ActionPerformed(evt);
            }
        });
        jPanel1.add(t60, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 10, 20));

        t0.setOpaque(false);
        t59.setBackground(new java.awt.Color(0,0,0,0));
        t59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t59ActionPerformed(evt);
            }
        });
        jPanel1.add(t59, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 10, 10));

        t0.setOpaque(false);
        t58.setBackground(new java.awt.Color(0,0,0,0));
        t58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t58ActionPerformed(evt);
            }
        });
        jPanel1.add(t58, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 10, 10));

        t0.setOpaque(false);
        t57.setBackground(new java.awt.Color(0,0,0,0));
        t57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t57ActionPerformed(evt);
            }
        });
        jPanel1.add(t57, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 20, 20));

        t0.setOpaque(false);
        t56.setBackground(new java.awt.Color(0,0,0,0));
        t56.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t56ActionPerformed(evt);
            }
        });
        jPanel1.add(t56, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 20, 10));

        t0.setOpaque(false);
        t55.setBackground(new java.awt.Color(0,0,0,0));
        t55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t55ActionPerformed(evt);
            }
        });
        jPanel1.add(t55, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 10, 10));

        t0.setOpaque(false);
        t54.setBackground(new java.awt.Color(0,0,0,0));
        t54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t54ActionPerformed(evt);
            }
        });
        jPanel1.add(t54, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 10, 20));

        t0.setOpaque(false);
        t53.setBackground(new java.awt.Color(0,0,0,0));
        t53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t53ActionPerformed(evt);
            }
        });
        jPanel1.add(t53, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 10, 10));

        t0.setOpaque(false);
        t52.setBackground(new java.awt.Color(0,0,0,0));
        t52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t52ActionPerformed(evt);
            }
        });
        jPanel1.add(t52, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 20, 20));

        t0.setOpaque(false);
        t51.setBackground(new java.awt.Color(0,0,0,0));
        t51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t51ActionPerformed(evt);
            }
        });
        jPanel1.add(t51, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 10, 10));

        t0.setOpaque(false);
        t50.setBackground(new java.awt.Color(0,0,0,0));
        t50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t50ActionPerformed(evt);
            }
        });
        jPanel1.add(t50, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 10, 10));

        t0.setOpaque(false);
        t49.setBackground(new java.awt.Color(0,0,0,0));
        t49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t49ActionPerformed(evt);
            }
        });
        jPanel1.add(t49, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 20, 20));

        t0.setOpaque(false);
        t48.setBackground(new java.awt.Color(0,0,0,0));
        t48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t48ActionPerformed(evt);
            }
        });
        jPanel1.add(t48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 20, 20));

        t0.setOpaque(false);
        t47.setBackground(new java.awt.Color(0,0,0,0));
        t47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t47ActionPerformed(evt);
            }
        });
        jPanel1.add(t47, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 20, 20));

        t0.setOpaque(false);
        t46.setBackground(new java.awt.Color(0,0,0,0));
        t46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t46ActionPerformed(evt);
            }
        });
        jPanel1.add(t46, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 10, 10));

        t0.setOpaque(false);
        t45.setBackground(new java.awt.Color(0,0,0,0));
        t45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t45ActionPerformed(evt);
            }
        });
        jPanel1.add(t45, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 10, 10));

        t0.setOpaque(false);
        t44.setBackground(new java.awt.Color(0,0,0,0));
        t44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t44ActionPerformed(evt);
            }
        });
        jPanel1.add(t44, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 20, 20));

        t0.setOpaque(false);
        t43.setBackground(new java.awt.Color(0,0,0,0));
        t43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t43ActionPerformed(evt);
            }
        });
        jPanel1.add(t43, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 10, 10));

        t0.setOpaque(false);
        t42.setBackground(new java.awt.Color(0,0,0,0));
        t42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t42ActionPerformed(evt);
            }
        });
        jPanel1.add(t42, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 10, 10));

        t0.setOpaque(false);
        t41.setBackground(new java.awt.Color(0,0,0,0));
        t41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t41ActionPerformed(evt);
            }
        });
        jPanel1.add(t41, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 10, 10));

        t0.setOpaque(false);
        t40.setBackground(new java.awt.Color(0,0,0,0));
        t40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t40ActionPerformed(evt);
            }
        });
        jPanel1.add(t40, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 10, 10));

        t0.setOpaque(false);
        t39.setBackground(new java.awt.Color(0,0,0,0));
        t39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t39ActionPerformed(evt);
            }
        });
        jPanel1.add(t39, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 30, 10));

        t0.setOpaque(false);
        t38.setBackground(new java.awt.Color(0,0,0,0));
        t38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t38ActionPerformed(evt);
            }
        });
        jPanel1.add(t38, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 30, 10));

        t0.setOpaque(false);
        t37.setBackground(new java.awt.Color(0,0,0,0));
        t37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t37ActionPerformed(evt);
            }
        });
        jPanel1.add(t37, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 30, 20));

        t0.setOpaque(false);
        t36.setBackground(new java.awt.Color(0,0,0,0));
        t36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t36ActionPerformed(evt);
            }
        });
        jPanel1.add(t36, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 20, 20));

        t0.setOpaque(false);
        t35.setBackground(new java.awt.Color(0,0,0,0));
        t35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t35ActionPerformed(evt);
            }
        });
        jPanel1.add(t35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 20, 20));

        t0.setOpaque(false);
        t34.setBackground(new java.awt.Color(0,0,0,0));
        t34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t34ActionPerformed(evt);
            }
        });
        jPanel1.add(t34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 20, 20));

        t0.setOpaque(false);
        t33.setBackground(new java.awt.Color(0,0,0,0));
        t33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t33ActionPerformed(evt);
            }
        });
        jPanel1.add(t33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 20, 20));

        t0.setOpaque(false);
        t32.setBackground(new java.awt.Color(0,0,0,0));
        t32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t32ActionPerformed(evt);
            }
        });
        jPanel1.add(t32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 20, 20));

        t0.setOpaque(false);
        t31.setBackground(new java.awt.Color(0,0,0,0));
        t31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t31ActionPerformed(evt);
            }
        });
        jPanel1.add(t31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 10, 10));

        t0.setOpaque(false);
        t30.setBackground(new java.awt.Color(0,0,0,0));
        t30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t30ActionPerformed(evt);
            }
        });
        jPanel1.add(t30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 10, 10));

        t0.setOpaque(false);
        t29.setBackground(new java.awt.Color(0,0,0,0));
        t29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t29ActionPerformed(evt);
            }
        });
        jPanel1.add(t29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 20, 10));

        t0.setOpaque(false);
        t28.setBackground(new java.awt.Color(0,0,0,0));
        t28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t28ActionPerformed(evt);
            }
        });
        jPanel1.add(t28, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 20, 10));

        t0.setOpaque(false);
        t27.setBackground(new java.awt.Color(0,0,0,0));
        t27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t27ActionPerformed(evt);
            }
        });
        jPanel1.add(t27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 20, 20));

        t0.setOpaque(false);
        t26.setBackground(new java.awt.Color(0,0,0,0));
        t26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t26ActionPerformed(evt);
            }
        });
        jPanel1.add(t26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 10, 20));

        t0.setOpaque(false);
        t25.setBackground(new java.awt.Color(0,0,0,0));
        t25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t25ActionPerformed(evt);
            }
        });
        jPanel1.add(t25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 10, 10));

        t0.setOpaque(false);
        t24.setBackground(new java.awt.Color(0,0,0,0));
        t24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t24ActionPerformed(evt);
            }
        });
        jPanel1.add(t24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 30, 10));

        t0.setOpaque(false);
        t23.setBackground(new java.awt.Color(0,0,0,0));
        t23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t23ActionPerformed(evt);
            }
        });
        jPanel1.add(t23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 20, 10));

        t0.setOpaque(false);
        t22.setBackground(new java.awt.Color(0,0,0,0));
        t22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t22ActionPerformed(evt);
            }
        });
        jPanel1.add(t22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 10, 10));

        t0.setOpaque(false);
        t21.setBackground(new java.awt.Color(0,0,0,0));
        t21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t21ActionPerformed(evt);
            }
        });
        jPanel1.add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 10, 10));

        t0.setOpaque(false);
        t20.setBackground(new java.awt.Color(0,0,0,0));
        t20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t20ActionPerformed(evt);
            }
        });
        jPanel1.add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 20, 20));

        t0.setOpaque(false);
        t19.setBackground(new java.awt.Color(0,0,0,0));
        t19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t19ActionPerformed(evt);
            }
        });
        jPanel1.add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 10, 20));

        t0.setOpaque(false);
        t18.setBackground(new java.awt.Color(0,0,0,0));
        t18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t18ActionPerformed(evt);
            }
        });
        jPanel1.add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 10, 20));

        t0.setOpaque(false);
        t17.setBackground(new java.awt.Color(0,0,0,0));
        t17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t17ActionPerformed(evt);
            }
        });
        jPanel1.add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 10, 20));

        t0.setOpaque(false);
        t16.setBackground(new java.awt.Color(0,0,0,0));
        t16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t16ActionPerformed(evt);
            }
        });
        jPanel1.add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 20, 20));

        t0.setOpaque(false);
        t15.setBackground(new java.awt.Color(0,0,0,0));
        t15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t15ActionPerformed(evt);
            }
        });
        jPanel1.add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 20, 20));

        t0.setOpaque(false);
        t14.setBackground(new java.awt.Color(0,0,0,0));
        t14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t14ActionPerformed(evt);
            }
        });
        jPanel1.add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 10, 20));

        t0.setOpaque(false);
        t13.setBackground(new java.awt.Color(0,0,0,0));
        t13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });
        jPanel1.add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 20, 20));

        t0.setOpaque(false);
        t12.setBackground(new java.awt.Color(0,0,0,0));
        t12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12ActionPerformed(evt);
            }
        });
        jPanel1.add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 20, 20));

        t0.setOpaque(false);
        t11.setBackground(new java.awt.Color(0,0,0,0));
        t11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        jPanel1.add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 10, 20));

        t0.setOpaque(false);
        t10.setBackground(new java.awt.Color(0,0,0,0));
        t10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });
        jPanel1.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 20, 20));

        t0.setOpaque(false);
        t9.setBackground(new java.awt.Color(0,0,0,0));
        t9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        jPanel1.add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 10, 20));

        t0.setOpaque(false);
        t8.setBackground(new java.awt.Color(0,0,0,0));
        t8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 10, 20));

        t0.setOpaque(false);
        t7.setBackground(new java.awt.Color(0,0,0,0));
        t7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        jPanel1.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 20, 10));

        t0.setOpaque(false);
        t6.setBackground(new java.awt.Color(0,0,0,0));
        t6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        jPanel1.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 20, 20));

        t0.setOpaque(false);
        t5.setBackground(new java.awt.Color(0,0,0,0));
        t5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel1.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 20, 20));

        t0.setOpaque(false);
        t4.setBackground(new java.awt.Color(0,0,0,0));
        t4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 20, 10));

        t0.setOpaque(false);
        t3.setBackground(new java.awt.Color(0,0,0,0));
        t3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 20, 20));

        t0.setOpaque(false);
        t2.setBackground(new java.awt.Color(0,0,0,0));
        t2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 20, 10));

        t0.setOpaque(false);
        t1.setBackground(new java.awt.Color(0,0,0,0));
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 20, 20));

        t0.setOpaque(false);
        t0.setBackground(new java.awt.Color(0,0,0,0));
        t0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t0ActionPerformed(evt);
            }
        });
        jPanel1.add(t0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 20, 20));

        spin.setModel(new javax.swing.SpinnerNumberModel(30, 30, 150, 30));
        jPanel1.add(spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, -1, -1));

        spinbut.setFont(new java.awt.Font("SKAUT Bold", 0, 10)); // NOI18N
        spinbut.setText("ok");
        spinbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinbutActionPerformed(evt);
            }
        });
        jPanel1.add(spinbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 50, -1));

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 200, 20));

        acc.setFont(new java.awt.Font("SKAUT Bold", 0, 18)); // NOI18N
        acc.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 330, 30));

        score.setFont(new java.awt.Font("SKAUT Bold", 0, 18)); // NOI18N
        score.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 30));
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, -1, -1));

        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/map1.jpg"))); // NOI18N
        map.setToolTipText(null);
        map.setMinimumSize(new java.awt.Dimension(719, 519));
        map.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapMouseClicked(evt);
            }
        });
        jPanel1.add(map, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t0ActionPerformed
        cont.setAnsw(0);
        log();

        System.out.println(cont.getAnsw());

    }//GEN-LAST:event_t0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cont.chooseCity();

        name.setText(cont.getCity().get(cont.getrChosen()).toString());
        score.setText("");
        System.out.println(cont.getCity().get(cont.getrChosen()).toString());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_formMouseClicked

    private void mapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapMouseClicked
        // TODO add your handling code here:
        System.out.println("loll");

        System.out.println(cont.isCorrect(cont.getAnsw()) + "loll");
        System.out.println(cont.model.getCities().get(cont.getAnsw()));
        


    }//GEN-LAST:event_mapMouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(1);
        log();
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(2);
        log();
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(3);
        log();
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(4);
        log();
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(5);
        log();
    }//GEN-LAST:event_t5ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(6);
        log();
    }//GEN-LAST:event_t6ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(7);
        log();
    }//GEN-LAST:event_t7ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(8);
        log();
    }//GEN-LAST:event_t8ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(9);
        log();
    }//GEN-LAST:event_t9ActionPerformed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(10);
        log();
    }//GEN-LAST:event_t10ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(11);
        log();
    }//GEN-LAST:event_t11ActionPerformed

    private void t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(12);
        log();
    }//GEN-LAST:event_t12ActionPerformed

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t13ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(13);
        log();
    }//GEN-LAST:event_t13ActionPerformed

    private void t14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t14ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(14);
        log();
    }//GEN-LAST:event_t14ActionPerformed

    private void t15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t15ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(15);
        log();
    }//GEN-LAST:event_t15ActionPerformed

    private void t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t16ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(16);
        log();
    }//GEN-LAST:event_t16ActionPerformed

    private void t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t17ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(17);
        log();
    }//GEN-LAST:event_t17ActionPerformed

    private void t18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t18ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(18);
        log();
    }//GEN-LAST:event_t18ActionPerformed

    private void t19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t19ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(19);
        log();
    }//GEN-LAST:event_t19ActionPerformed

    private void t20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t20ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(20);
        log();
    }//GEN-LAST:event_t20ActionPerformed

    private void t21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t21ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(21);
        log();
    }//GEN-LAST:event_t21ActionPerformed

    private void t22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t22ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(22);
        log();
    }//GEN-LAST:event_t22ActionPerformed

    private void t23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t23ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(23);
        log();
    }//GEN-LAST:event_t23ActionPerformed

    private void t24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t24ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(24);
        log();
    }//GEN-LAST:event_t24ActionPerformed

    private void t25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t25ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(25);
        log();
    }//GEN-LAST:event_t25ActionPerformed

    private void t28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t28ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(28);
        log();
    }//GEN-LAST:event_t28ActionPerformed

    private void t27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t27ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(27);
        log();
    }//GEN-LAST:event_t27ActionPerformed

    private void t26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t26ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(26);
        log();
    }//GEN-LAST:event_t26ActionPerformed

    private void t29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t29ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(29);
        log();
    }//GEN-LAST:event_t29ActionPerformed

    private void t30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t30ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(30);
        log();
    }//GEN-LAST:event_t30ActionPerformed

    private void t31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t31ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(31);
        log();
    }//GEN-LAST:event_t31ActionPerformed

    private void t32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t32ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(32);
        log();
    }//GEN-LAST:event_t32ActionPerformed

    private void t33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t33ActionPerformed
        // TODO add your handling code here:
                cont.setAnsw(33);
        log();
    }//GEN-LAST:event_t33ActionPerformed

    private void t34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t34ActionPerformed
        // TODO add your handling code here:
                cont.setAnsw(34);
        log();
    }//GEN-LAST:event_t34ActionPerformed

    private void t35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t35ActionPerformed
        // TODO add your handling code here:
                cont.setAnsw(35);
        log();
    }//GEN-LAST:event_t35ActionPerformed

    private void t36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t36ActionPerformed
        // TODO add your handling code here:
                cont.setAnsw(36);
        log();
    }//GEN-LAST:event_t36ActionPerformed

    private void spinbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinbutActionPerformed
        // TODO add your handling code here:
        cont.setSpinner(getSpin());
        System.out.println(getSpin());
    }//GEN-LAST:event_spinbutActionPerformed

    private void t37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t37ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(37);
        log();
    }//GEN-LAST:event_t37ActionPerformed

    private void t38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t38ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(38);
        log();
    }//GEN-LAST:event_t38ActionPerformed

    private void t39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t39ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(39);
        log();
    }//GEN-LAST:event_t39ActionPerformed

    private void t40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t40ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(40);
        log();
    }//GEN-LAST:event_t40ActionPerformed

    private void t41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t41ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(41);
        log();
    }//GEN-LAST:event_t41ActionPerformed

    private void t42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t42ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(42);
        log();
    }//GEN-LAST:event_t42ActionPerformed

    private void t43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t43ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(43);
        log();
    }//GEN-LAST:event_t43ActionPerformed

    private void t44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t44ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(44);
        log();
    }//GEN-LAST:event_t44ActionPerformed

    private void t45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t45ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(45);
        log();
    }//GEN-LAST:event_t45ActionPerformed

    private void t46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t46ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(46);
        log();
    }//GEN-LAST:event_t46ActionPerformed

    private void t47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t47ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(47);
        log();
    }//GEN-LAST:event_t47ActionPerformed

    private void t48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t48ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(48);
        log();
    }//GEN-LAST:event_t48ActionPerformed

    private void t49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t49ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(49);
        log();
    }//GEN-LAST:event_t49ActionPerformed

    private void t50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t50ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(50);
        log();
    }//GEN-LAST:event_t50ActionPerformed

    private void t51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t51ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(51);
        log();
    }//GEN-LAST:event_t51ActionPerformed

    private void t52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t52ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(52);
        log();
    }//GEN-LAST:event_t52ActionPerformed

    private void t53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t53ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(53);
        log();
    }//GEN-LAST:event_t53ActionPerformed

    private void t54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t54ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(54);
        log();
    }//GEN-LAST:event_t54ActionPerformed

    private void t55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t55ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(55);
        log();
    }//GEN-LAST:event_t55ActionPerformed

    private void t56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t56ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(56);
        log();
    }//GEN-LAST:event_t56ActionPerformed

    private void t57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t57ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(57);
        log();
    }//GEN-LAST:event_t57ActionPerformed

    private void t58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t58ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(58);
        log();
    }//GEN-LAST:event_t58ActionPerformed

    private void t59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t59ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(59);
        log();
    }//GEN-LAST:event_t59ActionPerformed

    private void t60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t60ActionPerformed
        // TODO add your handling code here:
        cont.setAnsw(60);
        log();
    }//GEN-LAST:event_t60ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel map;
    private javax.swing.JLabel name;
    private javax.swing.JLabel score;
    private javax.swing.JSpinner spin;
    private javax.swing.JButton spinbut;
    private javax.swing.JButton t0;
    private javax.swing.JButton t1;
    private javax.swing.JButton t10;
    private javax.swing.JButton t11;
    private javax.swing.JButton t12;
    private javax.swing.JButton t13;
    private javax.swing.JButton t14;
    private javax.swing.JButton t15;
    private javax.swing.JButton t16;
    private javax.swing.JButton t17;
    private javax.swing.JButton t18;
    private javax.swing.JButton t19;
    private javax.swing.JButton t2;
    private javax.swing.JButton t20;
    private javax.swing.JButton t21;
    private javax.swing.JButton t22;
    private javax.swing.JButton t23;
    private javax.swing.JButton t24;
    private javax.swing.JButton t25;
    private javax.swing.JButton t26;
    private javax.swing.JButton t27;
    private javax.swing.JButton t28;
    private javax.swing.JButton t29;
    private javax.swing.JButton t3;
    private javax.swing.JButton t30;
    private javax.swing.JButton t31;
    private javax.swing.JButton t32;
    private javax.swing.JButton t33;
    private javax.swing.JButton t34;
    private javax.swing.JButton t35;
    private javax.swing.JButton t36;
    private javax.swing.JButton t37;
    private javax.swing.JButton t38;
    private javax.swing.JButton t39;
    private javax.swing.JButton t4;
    private javax.swing.JButton t40;
    private javax.swing.JButton t41;
    private javax.swing.JButton t42;
    private javax.swing.JButton t43;
    private javax.swing.JButton t44;
    private javax.swing.JButton t45;
    private javax.swing.JButton t46;
    private javax.swing.JButton t47;
    private javax.swing.JButton t48;
    private javax.swing.JButton t49;
    private javax.swing.JButton t5;
    private javax.swing.JButton t50;
    private javax.swing.JButton t51;
    private javax.swing.JButton t52;
    private javax.swing.JButton t53;
    private javax.swing.JButton t54;
    private javax.swing.JButton t55;
    private javax.swing.JButton t56;
    private javax.swing.JButton t57;
    private javax.swing.JButton t58;
    private javax.swing.JButton t59;
    private javax.swing.JButton t6;
    private javax.swing.JButton t60;
    private javax.swing.JButton t7;
    private javax.swing.JButton t8;
    private javax.swing.JButton t9;
    // End of variables declaration//GEN-END:variables
}
